import Layout from "@/components/Common/Layout";
import Head from "next/head";
import Image from "next/image";
// import Link from 'next/link'
import ProfilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/Common/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Common/Icons";
import ContactMe from "@/components/Home/ContactMe";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nadeesha Profile | Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 ">
          <div className="flex items-center justify-between w-full ">
            <div className="w-1/2 ">
              <Image
                src={ProfilePic}
                alt="TanNghia"
                className="w-full h-auto "
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center ">
              <AnimatedText
                text={`Hi I'm Nadeesha, \nA Web & Mobile Developer.`}
                className="!text-6xl !text-left"
              />
              <p className="my-4 text-base font-medium">
                As a skilled fullstack developer, I am devoted to transforming
                ideas into cutting-edge applications for both web and mobile
                platforms. So here discover my latest projects, showcasing
                my proficiency and comprehensive expertise in web
                and mobile development.
              </p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/Nadeesha Madusanka Resume.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light
                 hover:text-dark border-2 border-solid border-transparent
                  hover:border-dark 
                  dark:bg-light dark:text-dark hover:dark:bg-dark
                   hover:dark:text-light hover:dark:border-light"
                >
                  Resume
                  <LinkArrow className={"w-6 ml-1"} />
                </Link>
               
              </div>
            </div>
          </div>
        </Layout>
        <ContactMe />
      </main>
    </>
  );
}
